import type { Contract, Notification } from '../types';
import { getContractStatus } from './contractStatus';

const today = new Date();
const y = today.getFullYear();

function addDays(d: Date, n: number) {
  const r = new Date(d); r.setDate(r.getDate() + n); return r;
}
function iso(d: Date) { return d.toISOString().split('T')[0]; }

const raw: Omit<Contract, 'status'>[] = [
  // ── Contracten ──
  {
    id: 'seed-1', type: 'contract',
    name: 'Vattenfall Energie', category: 'energie', provider: 'Vattenfall',
    startDate: `${y - 2}-03-01`, endDate: iso(addDays(today, 22)),
    noticePeriodDays: 30, monthlyAmount: 142,
    betaler: 'samen', beheerder: 'tom',
    notes: 'Variabel tarief, jaarlijks opzegbaar',
    docs: [], createdAt: `${y - 2}-03-01T00:00:00Z`, updatedAt: `${y - 2}-03-01T00:00:00Z`,
  },
  {
    id: 'seed-2', type: 'contract',
    name: 'KPN Mobiel', category: 'telefoon', provider: 'KPN',
    startDate: `${y - 1}-06-01`, endDate: iso(addDays(today, 48)),
    noticePeriodDays: 30, monthlyAmount: 38,
    betaler: 'tom', beheerder: 'tom',
    docs: [], createdAt: `${y - 1}-06-01T00:00:00Z`, updatedAt: `${y - 1}-06-01T00:00:00Z`,
  },
  {
    id: 'seed-3', type: 'contract',
    name: 'Hypotheek ABN AMRO', category: 'hypotheek', provider: 'ABN AMRO',
    startDate: `${y - 9}-04-01`, endDate: iso(addDays(today, 350)),
    noticePeriodDays: 90, monthlyAmount: 1240,
    betaler: 'samen', beheerder: 'tom',
    notes: 'Rentevaste periode loopt binnenkort af. Vergelijk nieuwe rentetarieven tijdig — circa 1 jaar voor afloop.',
    docs: [], createdAt: `${y - 9}-04-01T00:00:00Z`, updatedAt: `${y - 9}-04-01T00:00:00Z`,
  },
  {
    id: 'seed-4', type: 'contract',
    name: 'Zorgverzekering CZ', category: 'zorgverzekering', provider: 'CZ',
    startDate: `${y}-01-01`, endDate: `${y}-12-31`,
    noticePeriodDays: 30, monthlyAmount: 156,
    betaler: 'ilze', beheerder: 'ilze',
    notes: 'Jaarlijks opzegbaar voor 31 december',
    docs: [], createdAt: `${y}-01-01T00:00:00Z`, updatedAt: `${y}-01-01T00:00:00Z`,
  },
  {
    id: 'seed-5', type: 'contract',
    name: 'Autoverzekering ANWB', category: 'verzekering', provider: 'ANWB',
    startDate: `${y - 1}-11-01`, endDate: iso(addDays(today, 55)),
    noticePeriodDays: 30, monthlyAmount: 89,
    betaler: 'tom', beheerder: 'tom',
    docs: [], createdAt: `${y - 1}-11-01T00:00:00Z`, updatedAt: `${y - 1}-11-01T00:00:00Z`,
  },
  // ── Abonnementen ──
  {
    id: 'seed-6', type: 'abonnement',
    name: 'Netflix', category: 'streaming', provider: 'Netflix',
    startDate: `${y - 3}-01-01`, endDate: null,
    noticePeriodDays: 0, monthlyAmount: 18,
    betaler: 'tom', beheerder: 'tom',
    docs: [], createdAt: `${y - 3}-01-01T00:00:00Z`, updatedAt: `${y - 3}-01-01T00:00:00Z`,
  },
  {
    id: 'seed-7', type: 'abonnement',
    name: 'Spotify Family', category: 'streaming', provider: 'Spotify',
    startDate: `${y - 2}-03-01`, endDate: null,
    noticePeriodDays: 0, monthlyAmount: 17.99,
    betaler: 'ilze', beheerder: 'ilze',
    docs: [], createdAt: `${y - 2}-03-01T00:00:00Z`, updatedAt: `${y - 2}-03-01T00:00:00Z`,
  },
  {
    id: 'seed-8', type: 'abonnement',
    name: 'Basic-Fit', category: 'sport', provider: 'Basic-Fit',
    startDate: `${y - 1}-06-01`, endDate: null,
    noticePeriodDays: 30, monthlyAmount: 25.99,
    betaler: 'ilze', beheerder: 'ilze',
    docs: [], createdAt: `${y - 1}-06-01T00:00:00Z`, updatedAt: `${y - 1}-06-01T00:00:00Z`,
  },
  {
    id: 'seed-9', type: 'abonnement',
    name: 'Adobe Creative Cloud', category: 'software', provider: 'Adobe',
    startDate: `${y}-01-01`, endDate: iso(addDays(today, 58)),
    noticePeriodDays: 14, monthlyAmount: 54.99,
    betaler: 'tom', beheerder: 'tom',
    notes: 'Jaarplan — annuleringsvergoeding bij vroegtijdig opzeggen',
    docs: [], createdAt: `${y}-01-01T00:00:00Z`, updatedAt: `${y}-01-01T00:00:00Z`,
  },
  // ── Huurcontract (use case: verhuizing) ──
  {
    id: 'seed-10', type: 'contract',
    name: 'Huurcontract Amstelstraat 14', category: 'huur', provider: 'Woningnet Verhuur',
    startDate: `${y - 3}-06-01`, endDate: iso(addDays(today, 60)),
    noticePeriodDays: 30, monthlyAmount: 1450,
    betaler: 'samen', beheerder: 'ilze',
    tags: ['verhuizing', 'opzeggen'],
    notes: 'Verhuizing gepland. Zorg dat het contract uiterlijk 30 dagen voor de einddatum is opgezegd.',
    docs: [], createdAt: `${y - 3}-06-01T00:00:00Z`, updatedAt: `${y - 3}-06-01T00:00:00Z`,
  },
];

export const seedContracts: Contract[] = raw.map(c => ({ ...c, status: getContractStatus(c) }));

// Smart notifications are auto-generated by useContracts on first load.
// No static seed notifications needed.
export const seedNotifications: Notification[] = [];
